apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: hub
        url: https://kubernetes.default.svc
      - cluster: spoke-1
        url: https://7464728E735AE35919D2B6169BCEBB64.gr7.ap-south-1.eks.amazonaws.com      
      - cluster: spoke-2
        url: https://C73B6899D1E13C33DF8757B58632BFDC.gr7.ap-south-1.eks.amazonaws.com
  template:
    metadata:
      name: '{{cluster}}-guestbookdemo'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/jonathan-paule/argocd-example-apps.git
        targetRevision: master
        path: guestbook
      destination:
        server: '{{url}}'
        namespace: guestbook
      syncPolicy:
         syncOptions:
          - CreateNamespace=true
